# Generated by Django 4.0.2 on 2022-07-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='', max_length=20)),
                ('event', models.CharField(default='', max_length=100)),
                ('body', models.TextField(default='')),
            ],
        ),
    ]
