# Generated by Django 4.0.2 on 2022-07-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='forMonth',
            new_name='month',
        ),
    ]
