# Generated by Django 4.0.2 on 2022-07-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_notificationmodel_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='payer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
