# Generated by Django 4.0.2 on 2022-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_transactionmodel_payer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='mode',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='year',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='paid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='month',
            field=models.CharField(default='', max_length=20),
        ),
    ]
