# Generated by Django 4.0.2 on 2022-07-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_remove_transactionmodel_mode_notificationmodel_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='paid',
            field=models.CharField(default='Unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='paid',
            field=models.CharField(default='Unpaid', max_length=10),
        ),
    ]
