# Generated by Django 4.0.2 on 2022-08-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_bankmodel_transactionmodel_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeModel',
            fields=[
                ('chequeId', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('date', models.CharField(default='', max_length=15)),
                ('amount', models.IntegerField(default=0)),
                ('mode', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=200)),
                ('bankId', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='bankmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankmodel',
            name='bankId',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
