# Generated by Django 4.0.2 on 2022-08-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_accountmodel_assets_liabilities_delete_bankmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='accountId',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
