# Generated by Django 4.0.2 on 2022-08-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_remove_accountmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='building',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assets',
            name='computer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assets',
            name='furniture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assets',
            name='land',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assets',
            name='vehicles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='mode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
