# Generated by Django 4.0.2 on 2022-08-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_trialbalancemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalancemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='trialbalancemodel',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trialbalancemodel',
            name='trailBalanceId',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='trialbalancemodel',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
